### ISSUE TITLE
Exception when compiling

### ISSUE THREAD

**Issue by bnorm** [gabrielittner/auto-value-with#21]
Updated to the latest version of auto-value-with, 0.1.3, and hit this exception.

```
Caused by: java.lang.NoSuchMethodError: com.squareup.javapoet.CodeBlock.of(Ljava/lang/String;[Ljava/lang/Object;)Lcom/squareup/javapoet/CodeBlock;
        at com.gabrielittner.auto.value.util.AutoValueUtil.newConstructor(AutoValueUtil.java:100)
        at com.gabrielittner.auto.value.util.AutoValueUtil.newTypeSpecBuilder(AutoValueUtil.java:71)
        at com.gabrielittner.auto.value.with.AutoValueWithExtension.generateClass(AutoValueWithExtension.java:123)
        at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:424)
        at com.google.auto.value.processor.AutoValueProcessor.process(AutoValueProcessor.java:143)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
```

Dependencies in pom file.

```xml
...
    <dependency>
      <groupId>com.google.auto.value</groupId>
      <artifactId>auto-value</artifactId>
      <version>1.2</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.ryanharter.auto.value</groupId>
      <artifactId>auto-value-moshi</artifactId>
      <version>0.3.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.gabrielittner.auto.value</groupId>
      <artifactId>auto-value-with</artifactId>
      <version>0.1.3</version>
      <scope>provided</scope>
    </dependency>
...
```

I think it might be colliding with auto-value-moshi which brings in javapoet:1.7.0.  I tried to exclude javapoet from auto-value-moshi and also tried an explicit dependency on javapoet:1.6.0 and neither worked.  I can provide more specifics on the project if you need.

**Comment by gabrielittner** [comment]
JavaPoet 1.7 has that method, so it has to be another dependency. Can you give me a full list of dependencies? I've seen this before with Dagger 2 before version 2.4.

**Comment by bnorm** [comment]
Here's the branch of the project I am trying to update.  https://github.com/bnorm-software/barkeep-testing/tree/withers-update  You can look at the pom file to see what dependencies I have.

**Comment by gabrielittner** [comment]
Two solutions that fix it for me:
1) Update to Dagger 2.4
2) Add JavaPoet before Dagger to the dependencies.
```xml    
    <dependency>
      <groupId>com.squareup</groupId>
      <artifactId>javapoet</artifactId>
      <version>1.7.0</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>com.google.dagger</groupId>
      <artifactId>dagger</artifactId>
      <version>${dagger.version}</version>
    </dependency>
    <dependency>
      <groupId>com.google.dagger</groupId>
      <artifactId>dagger-compiler</artifactId>
      <version>${dagger.version}</version>
      <scope>provided</scope>
    </dependency>
```

The latter is probably safer because Dagger 2.4 uses JavaPoet 1.6, so it will fail again if any annotation processor uses something added in JavaPoet 1.7.

**Comment by bnorm** [comment]
Awesome.  That worked for me as well.  Thanks!
